### ISSUE TITLE
Roadmap Wallpaper App

### ISSUE THREAD

**Issue by enzarafaela** [enzarafaela/react-router-wallpaper-app#4]
- [x] Substituindo os dados locais pela unsplash API
 #1 
 
- [x] Infinity scroll: adicionando um event listener para o evento scroll;
- [x] A cada vez que chegar ao final da página, carrega mais uma página de wallpapers;
- [x] Hook useEffect para acionar carregamento de novos wallpapers uma única vez;
- [x] Adicionando cleanup na useEffect para remover o event listenet;
- [x] Controlando páginas com useState;
#2

- [x] Melhoria de código
#3
